### PR TITLE
fix: pass missing gts argument to _dump_generations call

### LINKED ISSUE #492: RayPPOTrainer._dump_generations() missing gts argument in _train_step call
## Bug Report

**Describe the bug**

In `agentlightning/verl/trainer.py`, `_train_step` calls `_dump_generations` without passing the required `gts` argument, causing a `TypeError` at runtime when `trainer.rollout_data_dir` is set.

**Error message**

```
File "agentlightning/verl/trainer.py", line 421, in _train_step
    self._dump_generations(
TypeError: RayPPOTrainer._dump_generations() missing 1 required positional argument: 'gts'
```

**Steps to Reproduce**

1. Set `rollout_data_dir` in the trainer config
2. Run training — the error is triggered at the rollout generation dump step

**Root Cause**

`_dump_generations` is defined with `gts` as a required positional argument:

```python
def _dump_generations(self, inputs, outputs, gts, scores, reward_extra_infos_dict, dump_path):
```

But the call site in `_train_step` does not pass `gts`:

```python
self._dump_generations(
    inputs=inputs,
    outputs=outputs,
    scores=scores,
    reward_extra_infos_dict=reward_extra_infos_dict,
    dump_path=rollout_data_dir,
)
```

**Suggested Fix**

Either pass `gts=None` at the call site, or give `gts` a default value of `None` in the function signature to make it optional when ground truth is unavailable.

**Environment**
- Version: v0.3.0
- File: `agentlightning/verl/trainer.py`
- Class: `RayPPOTrainer`

### PR DESCRIPTION
**Pull request by Alexi5000**
## Summary

- Fix a runtime `TypeError` in `_dump_generations()` that occurs when `rollout_data_dir` is configured, in both `AgentLightningTrainer._train_step` and `EnvAgentLightningTrainer._train_step`
- Make the fix **version-robust** across verl 0.5.0 and 0.6.0 (see Problem below)
- Remove a leftover `print(batch.batch.keys())` debug statement from both call sites

> **Note:** This PR supersedes the duplicate PRs #493 and #522, which addressed the same bug. This version additionally handles the verl 0.5.0 / 0.6.0 signature difference so it does not break the CI-pinned verl 0.5.0.

## Problem

`RayPPOTrainer._dump_generations()` is called from both trainer subclasses, but its signature changed between verl releases:

- **verl 0.5.0** (CI-pinned in `examples-compat.yml`): `_dump_generations(self, inputs, outputs, scores, reward_extra_infos_dict, dump_path)` — **no** `gts` parameter
- **verl >=0.6.0**: `_dump_generations(self, inputs, outputs, gts, scores, reward_extra_infos_dict, dump_path)` — adds a required `gts` (ground truths) positional parameter

The original call sites omitted `gts` entirely, which raises a `TypeError` on verl 0.6.0:

```
TypeError: RayPPOTrainer._dump_generations() missing 1 required positional argument: 'gts'
```

Conversely, unconditionally passing `gts=None` breaks on verl 0.5.0:

```
TypeError: _dump_generations() got an unexpected keyword argument 'gts'
```

Ground truth is not available in agent-mode training, so `None` is the correct value when the parameter exists.

## Fix

Feature-detect the `_dump_generations` signature with `inspect.signature(...)` and only pass `gts=None` when the `gts` parameter is present. This works on both verl 0.5.0 and 0.6.0:

```python
dump_kwargs = dict(
    inputs=inputs,
    outputs=outputs,
    scores=scores,
    reward_extra_infos_dict=reward_extra_infos_dict,
    dump_path=rollout_data_dir,
)
if "gts" in inspect.signature(self._dump_generations).parameters:
    dump_kwargs["gts"] = None
self._dump_generations(**dump_kwargs)
```

Fixes #492

## Files Changed

- `agentlightning/verl/trainer.py` — `AgentLightningTrainer._train_step`
- `contrib/agentlightning/contrib/algorithm/env_verl/trainer.py` — `EnvAgentLightningTrainer._train_step`

## Test plan

- [ ] Run training with `rollout_data_dir` configured on **verl 0.5.0** — no `TypeError`
- [ ] Run training with `rollout_data_dir` configured on **verl 0.6.0** — no `TypeError`, `gts=None` passed
- [ ] Run training without `rollout_data_dir` — no behavior change

### CODE REVIEW

**Comment by Alexi5000** [comment]
@microsoft-github-policy-service agree

**Comment by Alexi5000** [comment]
@microsoft-github-policy-service agree
